### ISSUE TITLE
Which features were corrected?

### ISSUE THREAD

**Issue by DimaSheiko** [Magmonix/TSM2_WotLK_3.3.5a#1]
Which features were corrected?

**Comment by Magmonix** [comment]
Dima, the only things I remember for sure are Sniper and item searching. That being said, TSM has released newer versions of TSM4 for Classic. If you're using this for a private server I would suggest swapping to TSM4 when WotLK Classic launches and TSM4 is inevitably released for WotLK.

**Comment by DimaSheiko** [comment]
> Dima, the only things I remember for sure are Sniper and item searching. That being said, TSM has released newer versions of TSM4 for Classic. If you're using this for a private server I would suggest swapping to TSM4 when WotLK Classic launches and TSM4 is inevitably released for WotLK.

Believe me I am looking forward to the release of Wotlk Classic so I can use the full range of addons. I hope they are compatible with the old version of wotlk.
